//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package org.leonehouse.annotationtest;

import java.util.HashMap;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class MyRestClient_
    implements MyRestClient
{

    private String rootUrl;
    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;

    public MyRestClient_() {
        rootUrl = "http://company.com/ajax/services";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
    }

    @Override
    public Object getEvents() {
        try {
            return restTemplate.exchange(rootUrl.concat("/events"), HttpMethod.GET, null, Object.class).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public Object getEventsByYearAndLocation(int year, String location) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("location", location);
        urlVariables.put("year", year);
        try {
            return restTemplate.exchange(rootUrl.concat("/events/{year}/{location}"), HttpMethod.GET, null, Object.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public Object getEventsByLocationAndYear(String location, int year) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("location", location);
        urlVariables.put("year", year);
        try {
            return restTemplate.exchange(rootUrl.concat("/events/{year}/{location}"), HttpMethod.GET, null, Object.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
